services:
  api1:
    image: diogoloff/api-delphi-rinha2025:latest
    hostname: api1
    ports:
      - "9999:8080"
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - CON_TIME_OUT=5000
      - READ_TIME_OUT=2500
      - NUM_WORKERS=12
      - LISTEM_QUEUE=32
      - NUM_TENTATIVAS_DEFAULT=5
      - TEMPO_FILA=10
      - DEBUG=N
    volumes:
     - ./Logs/:/opt/rinha/Logs/  #somente se DEBUG=S
    networks:
      - backend-rinha
      - payment-processor
    #deploy:
    #  resources:
    #    limits:
    #      cpus: "0.50"
    #      memory: "100MB"

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
