services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend-rinha
    deploy:
      resources:
       limits:
          cpus: "0.15"
          memory: "50MB"

  api1: &api
    image: diogoloff/api-delphi-rinha2025:latest
    hostname: api1
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - CON_TIME_OUT=5000
      - READ_TIME_OUT=200
      - NUM_WORKERS=12
      - LISTEM_QUEUE=2
      - NUM_TENTATIVAS_DEFAULT=10 # 5
      - TEMPO_FILA=10
      - DEBUG=N
    volumes:
      - shm-volume:/dev/shm
      #- ./Logs/:/opt/rinha/Logs/  #somente se DEBUG=S
    networks:
      - backend-rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.675" 
          memory: "150MB"
    
  api2:
    <<: *api
    hostname: api2
    volumes:
      - shm-volume:/dev/shm
      #- ./Logs2/:/opt/rinha/Logs/ #somente se DEBUG=S

volumes:
  shm-volume:
    driver: local

networks:
  backend-rinha:
    name: backend-rinha
    driver: bridge
  payment-processor:
    external: true
